baseURL = 'https://bigfa.github.io/'
languageCode = 'zh-cn'
timezone = 'Asia/Shanghai'
defaultContentLanguage = 'zh-cn'
theme = 'farallon'


[langusges]
[languages.en]
  title = "Untitled"
  languageName = "English"
  contentDir = 'content/en'
  [languages.en.menu]
    [[languages.en.menu.main]]
    name="Gears"
    url="/en/gears/"
    weight="2"
    [[languages.en.menu.main]]
    name="Movies"
    url="/en/movies/"
    weight="1"
    [[languages.en.menu.main]]
    name="Categories"
    url="/en/categories/"
    weight="1"
    [[languages.en.menu.main]]
    name="Tags"
    url="/en/tags/"
    weight="1"
    [[languages.en.menu.main]]
    name="About"
    url="/en/about/"
    weight="3"
    [[languages.en.menu.main]]
    name="Stories"
    url="/en/archive/"
    weight="1"

[languages.zh-cn]
  title = "Untitled"
  languageName = "简体中文"
  contentDir = 'content/zh-cn'
  [languages.zh-cn.menu]
    [[languages.zh-cn.menu.main]]
    name="设备"
    url="/gears/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="书影音"
    url="/movies/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="分类"
    url="/categories/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="标签"
    url="/tags/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="文章"
    url="/archive/"
    weight="1"

[taxonomies]
  category = 'categories'
  tag = 'tags'

[outputs]
  home = [ "HTML","JSON","RSS","SITEMAP"]
  page = ["HTML"]


[markup.tableOfContents]
  endLevel = 5
  startLevel = 3

[permalinks]
  [permalinks.section]
    post = '/archive'
  [permalinks.page]
    post = '/story/:filename/'
    page = '/:filename/'  
  [permalinks.term]
    tags = '/tag/:slug/'
    categories = '/category/:slug/'
