baseURL = 'https://bigfa.github.io/'
languageCode = 'zh-cn'
timezone = 'Asia/Shanghai'
defaultContentLanguage = 'zh-cn'
theme = 'farallon'

[langusges]
[languages.en]
  title = "bigfa's Blog"
  languageName = "English"
  contentDir = 'content/en'
  [languages.en.menu]
    [[languages.en.menu.main]]
    name="Gears"
    url="/en/gears/"
    weight="2"
    [[languages.en.menu.main]]
    name="Movies"
    url="/en/movies/"
    weight="1"
    [[languages.en.menu.main]]
    name="Categories"
    url="/categories/"
    weight="1"
    [[languages.en.menu.main]]
    name="About"
    url="/en/about/"
    weight="3"

[languages.zh-cn]
  title = "bigfa 的博客"
  languageName = "简体中文"
  contentDir = 'content/zh-cn'
  [languages.zh-cn.menu]
    [[languages.zh-cn.menu.main]]
    name="设备"
    url="/gears/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="书影音"
    url="/movies/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="分类"
    url="/categories/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="关于"
    url="/about/"
    weight="1"

[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

[Params]
  search=false
  description = 'A simple and fast blog framework written in Go.'
  toc = true

[outputs]
  home = [ "HTML","JSON","RSS","SITEMAP"]
  page = ["HTML"]